name: Checkmarx SAST Scan
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Checkmarx Action
      uses: checkmarx-ts/checkmarx-github-action@v1.0.0
      with:
        cxServer: https://cxprivatecloud.checkmarx.net/
        cxToken: ${{ secrets.CX_TOKEN }}
        cxTeam: \CxServer\SP\EMEA\checkmarx.com-855
        cxIncremental: true
        cxProject: WebGoatNet
